variable "project_name" {
  description = "Slug used to namespace every resource (bucket names, log groups, IAM roles)."
  type        = string
  default     = "handmade-jewelry-store"
}

variable "environment" {
  description = "Logical environment — 'production' / 'staging'. Tagged on every resource."
  type        = string
  default     = "production"
}

variable "aws_region" {
  description = "Primary AWS region. CloudFront/ACM-for-CF always run in us-east-1 regardless."
  type        = string
  default     = "us-east-1"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC. /16 leaves room for ~65k IPs across all subnets."
  type        = string
  default     = "10.0.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "CIDR for the two public subnets (AZ-a, AZ-b). Used by the ALB."
  type        = list(string)
  default     = ["10.0.1.0/24", "10.0.2.0/24"]
}

variable "private_subnet_cidrs" {
  description = "CIDR for the two private subnets (AZ-a, AZ-b). Used by ECS tasks and RDS."
  type        = list(string)
  default     = ["10.0.11.0/24", "10.0.12.0/24"]
}

variable "db_instance_class" {
  description = "RDS instance class. db.t3.micro = ~$13/mo, suitable for pre-launch traffic."
  type        = string
  default     = "db.t3.micro"
}

variable "db_name" {
  description = "Initial PostgreSQL database name created by RDS."
  type        = string
  default     = "jewelry"
}

variable "db_username" {
  description = "Master DB user. The password is generated by Terraform and stored in Secrets Manager."
  type        = string
  default     = "jewelry_app"
}

variable "db_allocated_storage_gb" {
  description = "Initial RDS storage in GB. Storage autoscaling is enabled — this is just the floor."
  type        = number
  default     = 20
}

variable "ecs_task_cpu" {
  description = "Fargate task CPU in cpu-units. 256 = 0.25 vCPU."
  type        = string
  default     = "256"
}

variable "ecs_task_memory" {
  description = "Fargate task memory in MiB. Must be valid pairing with cpu."
  type        = string
  default     = "512"
}

variable "ecs_desired_count" {
  description = "Number of Fargate tasks running. 1 task = no zero-downtime deploys; bump after first revenue."
  type        = number
  default     = 1
}

variable "api_container_port" {
  description = "Port the NestJS app listens on inside the container (see apps/api/src/main.ts)."
  type        = number
  default     = 4000
}

variable "domain_name" {
  description = "Apex domain for the production site (e.g. senichka.com). Leave '' to skip Route53/ACM provisioning."
  type        = string
  default     = ""
}

variable "manage_dns_in_aws" {
  description = "Set true when DNS lives in Route53. False means certificates use DNS validation in an external DNS provider (Cloudflare etc.) — you'll apply records manually."
  type        = bool
  default     = false
}

variable "alarm_email" {
  description = "SNS subscription email for CloudWatch alarms (#89). Leave '' to skip alarms entirely."
  type        = string
  default     = ""
}

variable "cors_origins" {
  description = "Allowed origins for S3 product-images PUT/GET. Includes preview/prod web hosts."
  type        = list(string)
  default = [
    "http://localhost:3100",
    "http://localhost:3000",
    "https://senichka.com",
    "https://www.senichka.com",
    "https://senichka.vercel.app",
  ]
}
